# Generated by Django 5.2.10 on 2026-03-09 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EVChargingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Latitude coordinate (-90 to 90)",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Longitude coordinate (-180 to 180)",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "charger_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1 (J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs", "CCS (Combined Charging System)"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla Supercharger"),
                            ("universal", "Universal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "power_level",
                    models.CharField(
                        choices=[
                            ("level1", "Level 1 (120V)"),
                            ("level2", "Level 2 (240V)"),
                            ("dcfast", "DC Fast Charging"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number_of_ports",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of available charging ports"
                    ),
                ),
                (
                    "charging_speed",
                    models.CharField(
                        help_text="e.g., '50 kW' or '150 kW'", max_length=50
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(
                        default=True,
                        help_text="Is this charging station currently operational?",
                    ),
                ),
                (
                    "cost_per_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per kilowatt-hour",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        help_text="Company or organization operating this station",
                        max_length=100,
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "available_24_7",
                    models.BooleanField(
                        default=False,
                        help_text="Is this station available 24 hours a day?",
                    ),
                ),
                (
                    "requires_membership",
                    models.BooleanField(
                        default=False,
                        help_text="Does this station require membership to use?",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Charging Station",
                "verbose_name_plural": "EV Charging Stations",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_point", models.CharField(max_length=200)),
                ("end_point", models.CharField(max_length=200)),
                ("start_lat", models.FloatField()),
                ("start_lng", models.FloatField()),
                ("end_lat", models.FloatField()),
                ("end_lng", models.FloatField()),
                (
                    "total_distance",
                    models.FloatField(help_text="Total distance in kilometers"),
                ),
                (
                    "estimated_time",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated travel time in minutes",
                        null=True,
                    ),
                ),
                (
                    "path_coordinates",
                    models.JSONField(
                        default=list,
                        help_text="List of waypoints with latitude/longitude coordinates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username or identifier of who created this route",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TouristAttraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Latitude coordinate (-90 to 90)",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Longitude coordinate (-180 to 180)",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("historical", "Historical Site"),
                            ("natural", "Natural Wonder"),
                            ("museum", "Museum"),
                            ("religious", "Religious Site"),
                            ("entertainment", "Entertainment"),
                            ("adventure", "Adventure Activity"),
                            ("cultural", "Cultural Site"),
                            ("beach", "Beach"),
                            ("park", "Park/Garden"),
                            ("viewpoint", "Viewpoint"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rating out of 5.0",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Entry fee in local currency",
                        max_digits=10,
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image of the attraction",
                        null=True,
                        upload_to="attractions/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tourist Attraction",
                "verbose_name_plural": "Tourist Attractions",
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of this waypoint in the route (1, 2, 3, ...)"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="maps.route",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
